# BMI = Weight / (Height ** 2)
user_weight = float(input("Please input your weight(kg):"))
user_height = float(input("Please input your height(meter):"))
user_BMI = user_weight / (user_height ** 2)
print("Your BMI is ", user_BMI)
